image: docker:latest

services:
  - docker:dind

stages:
  - build
 # - test
 # - push

variables:
  image_name: jenkins

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - build/
  script:
    - docker build -t ${image_name}:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest