version: "3"
services:
  node:
    build:
      context: .
      dockerfile: dockerfile
    #user: "node"
    networks:
      - back-tier
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - front-tier
      - back-tier
    depends_on:
      - node
    environment:
      - BALANCE=leastconn

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
    internal: true