version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/dockerfile
    ports:
      - 80:80
    networks:
      - front-tier
    environment:
      - NGINX_HOST=todo.com
      - NGINX_PORT=80
    volumes:
      - /var/www/todo/front:/etc/nginx/conf.d/todo.com/
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
      - node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3317:80
    networks:
      - back-tier 
    depends_on:
      - node
    environment:
      - BALANCE=leastconn
  node:
    build:
      context: .
      dockerfile: ./node/dockerfile
    networks:
      - back-tier
    environment:
      - NODE_ENV=production

networks:
  back-tier:
    driver: bridge
  front-tier:
    driver: bridge