---
# create aws ec2 instance
- name: Upload public key to AWS
  ec2_key:
    name: "{{ key_name }}"
    key_material: "{{ lookup('file', '/home/ansible/.ssh/{{ key_name }}.pub') }}"
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"

- name: Create security group
  ec2_group:
    name: "{{ sec_group }}"
    description: "Sec group for app {{ id }}"
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    rules:
      - proto: tcp
        ports:
          - 22
          - 80
          - 443
          - 3317
          - 3306
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all
  register: result_sec_group

- name: Provision instances
  ec2:
    aws_access_key: "{{ec2_access_key}}"
    aws_secret_key: "{{ec2_secret_key}}"
    key_name: "{{ key_name }}"
    group_id: "{{ result_sec_group.group_id }}"
    image: "{{ image }}"
    instance_type: t2.micro
    region: "{{ region }}"
    wait: true
    instance_tags:
      Name: "{{ item.key }}"
    exact_count: "{{ item.value.count }}"
    count_tag: "{{ item.key }}"
  with_dict: "{{ EC2_VMS }}"
...